services:
  flutter:
      build:
        context: ../../
        dockerfile: .devcontainer/frontend/Dockerfile
      environment:
        - HOME=/root
        - no_proxy=127.0.0.1,localhost
        - DISPLAY=host.docker.internal:0
        - LIBGL_ALWAYS_INDIRECT=1
        - QT_QUICK_BACKEND=software
        - QT_X11_NO_MITSHM=1
        - GETTOPIC_ENDPOINT_URL=http://backend:8000/
      command: sleep infinity
      volumes:
        - ../../:/workspace:cached
        - ~/.Xauthority:/root/.Xauthority
      extra_hosts:
        - flutter:127.0.1.1
      depends_on:
        - backend
  backend:
    container_name: backend
    build:
      context: ../../
      dockerfile: .devcontainer/backend/Dockerfile
    environment:
      - HOME=/root
    env_file:
      - .env
    command: uvicorn main:app --reload --port 8000 --host=0.0.0.0
    volumes:
      - ../../:/workspace:cached
      - getyourtopic-pip-front:/usr/local/lib/
    ports:
      - 8000:8000
volumes:
  getyourtopic-pip-front:
  
  # python:
  #   build:
  #     context: .
  #     dockerfile: DockerfilePython
  #   environment:
  #     - HOME=/root
  #     - no_proxy=127.0.0.1,localhost
  #     - DISPLAY=host.docker.internal:0
  #   volumes:
  #     - ${workspaceFolder}:/workspace:cached

  # db:
  #   image: mysql:8.0.36-debian
  #   environment:
  #     TZ: Asia/Tokyo
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: stock_data
  #     MYSQL_USER: stock_data_user
  #     MYSQL_PASSWORD: stock_data_user
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - stock-alert-db-data:/var/lib/mysql
  #     - ./initdb.d:/docker-entrypoint-initdb.d
  #   command:
  #     ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+09:00']
  
# volumes:
#   stock-alert-db-data:
