services:
  frontend:
    build:
      context: /frontend_getyourtopic
      dockerfile: /Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
        - network_production
  
  backend:
    build:
      context: /backend-claude-api
      dockerfile: /Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - network_production
networks:
  network_test:
    external: true
  network_production:
    external: true
