services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOME=/root
    env_file:
      - .env
    command: sleep infinity
    volumes:
      - ../../:/workspace:cached
      - getyourtopic-pip:/usr/local/lib/
volumes:
  getyourtopic-pip:

  # db:
  #   image: mysql:8.0.36-debian
  #   environment:
  #     TZ: Asia/Tokyo
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: stock_data
  #     MYSQL_USER: stock_data_user
  #     MYSQL_PASSWORD: stock_data_user
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - stock-alert-db-data:/var/lib/mysql
  #     - ./initdb.d:/docker-entrypoint-initdb.d
  #   command:
  #     ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci','--default-time-zone=+09:00']
