services:
  python:
    build:
      context: ../../
      dockerfile: .devcontainer/backend/Dockerfile
    environment:
      - HOME=/root
    env_file:
      - .env
    command: uvicorn main:app --reload --port 8000 --host=0.0.0.0
    volumes:
      - ../../:/workspace:cached
      - getyourtopic-pip:/usr/local/lib/
    ports:
      - 8001:8001
volumes:
  getyourtopic-pip:
